apiVersion: apps/v1
kind: Deployment
metadata:
name: backend
spec:
replicas: 1
selector:
matchLabels:
app: backend
template:
metadata:
labels:
app: backend
spec:
containers:
- name: backend
image: ${ACR_LOGIN_SERVER}/collegerecords-backend:v1
ports:
- containerPort: 3000
env:
- name: KEYVAULT_URI
value: "${KEYVAULT_URI}"
---
apiVersion: v1
kind: Service
metadata:
name: backend-svc
spec:
type: LoadBalancer
selector:
app: backend
ports:
- protocol: TCP
port: 80
targetPort: 3000